import Head from 'next/head'
import { Box } from '~/components/Box'
import { Button } from '~/components/Button'
import { Heading } from '~/components/Heading'
import { TextInput } from '~/components/TextInput'
import { Text } from '~/components/Text'
import { MagnifyingGlass } from 'phosphor-react'
import { Tag } from '~/components/Tag'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main
        style={{
          background: '#c9c9c9',
          display: 'flex',
          flexDirection: 'column',
          gap: '.5rem',
        }}
      >
        <Box size={'md'}>
          <Text>Hello</Text>
          <Button size={'md'} variant={'primary'}>
            Medium Primary
          </Button>
        </Box>

        <Box size={'sm'}>
          <Text size={'2xl'} color={'purple100'}>
            Hello
          </Text>
          <Button size={'sm'} variant={'primary'}>
            Small Primary
          </Button>
        </Box>

        <Box variant={'secondary'} size={'md'}>
          <Text>Hello</Text>

          <Button size={'md'} variant={'secondary'}>
            Medium Secondary
          </Button>
        </Box>

        <Box variant={'secondary'} size={'sm'}>
          <Text>Hello</Text>

          <Button size={'sm'} variant={'secondary'}>
            Small Secondary
          </Button>
        </Box>

        <Box variant={'secondary'} size={'sm'}>
          <Text>Hello</Text>

          <Button size={'lg'} variant={'terceary'}>
            S
          </Button>

          <Heading>Empty</Heading>
          <TextInput placeholder="Placeholder" />

          <Heading>Filled</Heading>
          <TextInput value={'Text'} />

          <Heading>With Icon</Heading>
          <TextInput value={'Text'} icon={MagnifyingGlass} />
        </Box>

        <Box css={{ flexDirection: 'column', gap: 5 }}>
          <Tag>Tag11</Tag>
          <Tag selected>Tag2</Tag>
        </Box>
      </main>
    </>
  )
}
